// AUTO-GENERATED by scripts/convert-puz.ts — do not edit by hand.
// Re-run:  npm run convert-puzzles
import type { GuardianCrossword } from '~/types';

export type PuzzleEntry = {
  id: string;
  name: string;
  data: GuardianCrossword;
};

export const puzzles: PuzzleEntry[] = [
  {
    id: '2025-12-01-mini',
    name: "NYT Mini – December 1, 2025",
    data: {
      "id": "2025-12-01-mini",
      "number": 1764576000000,
      "name": "NYT Mini – December 1, 2025",
      "crosswordType": "nyt-mini",
      "date": 1764576000000,
      "dimensions": {
        "cols": 5,
        "rows": 5
      },
      "solutionAvailable": true,
      "entries": [
        {
          "id": "1-across",
          "number": 1,
          "humanNumber": "1",
          "direction": "across",
          "clue": "Tree that's a symbol of Canada",
          "position": {
            "x": 0,
            "y": 0
          },
          "length": 5,
          "solution": "MAPLE",
          "group": [
            "1-across"
          ],
          "separatorLocations": {}
        },
        {
          "id": "1-down",
          "number": 1,
          "humanNumber": "1",
          "direction": "down",
          "clue": "Show mutual interest, as on a dating app",
          "position": {
            "x": 0,
            "y": 0
          },
          "length": 5,
          "solution": "MATCH",
          "group": [
            "1-down"
          ],
          "separatorLocations": {}
        },
        {
          "id": "2-down",
          "number": 2,
          "humanNumber": "2",
          "direction": "down",
          "clue": "\"Bad\" or \"Good Kid, M.A.A.D City\"",
          "position": {
            "x": 1,
            "y": 0
          },
          "length": 5,
          "solution": "ALBUM",
          "group": [
            "2-down"
          ],
          "separatorLocations": {}
        },
        {
          "id": "3-down",
          "number": 3,
          "humanNumber": "3",
          "direction": "down",
          "clue": "Sits (down) heavily",
          "position": {
            "x": 2,
            "y": 0
          },
          "length": 5,
          "solution": "PLOPS",
          "group": [
            "3-down"
          ],
          "separatorLocations": {}
        },
        {
          "id": "4-down",
          "number": 4,
          "humanNumber": "4",
          "direction": "down",
          "clue": "Contact ___",
          "position": {
            "x": 3,
            "y": 0
          },
          "length": 4,
          "solution": "LENS",
          "group": [
            "4-down"
          ],
          "separatorLocations": {}
        },
        {
          "id": "5-down",
          "number": 5,
          "humanNumber": "5",
          "direction": "down",
          "clue": "Look here!",
          "position": {
            "x": 4,
            "y": 0
          },
          "length": 3,
          "solution": "EYE",
          "group": [
            "5-down"
          ],
          "separatorLocations": {}
        },
        {
          "id": "6-across",
          "number": 6,
          "humanNumber": "6",
          "direction": "across",
          "clue": "Back street",
          "position": {
            "x": 0,
            "y": 1
          },
          "length": 5,
          "solution": "ALLEY",
          "group": [
            "6-across"
          ],
          "separatorLocations": {}
        },
        {
          "id": "7-across",
          "number": 7,
          "humanNumber": "7",
          "direction": "across",
          "clue": "Kind of steak with a letter in its name",
          "position": {
            "x": 0,
            "y": 2
          },
          "length": 5,
          "solution": "TBONE",
          "group": [
            "7-across"
          ],
          "separatorLocations": {}
        },
        {
          "id": "8-across",
          "number": 8,
          "humanNumber": "8",
          "direction": "across",
          "clue": "Beer pong targets",
          "position": {
            "x": 0,
            "y": 3
          },
          "length": 4,
          "solution": "CUPS",
          "group": [
            "8-across"
          ],
          "separatorLocations": {}
        },
        {
          "id": "9-across",
          "number": 9,
          "humanNumber": "9",
          "direction": "across",
          "clue": "\"___ Pinafore\" (Gilbert and Sullivan opera)",
          "position": {
            "x": 0,
            "y": 4
          },
          "length": 3,
          "solution": "HMS",
          "group": [
            "9-across"
          ],
          "separatorLocations": {}
        }
      ]
    } as GuardianCrossword,
  }
];
